- name: package installation
  hosts: local
  connection: local
  become: true
  tasks:
    - name: package installation
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - mssql-server
        - nginx
        - zip