- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: "ansible, devops, aws"
  tasks:
    - name: Gretting
      ansible.builtin.debug:
        msg: "Hello leeladhar, {{ Gretting | default('good morning') }}"
      
    - name: convert string to list
      ansible.builtin.debug:
        msg: "{{ topics | split(',') }}"


    - name: Read student yaml file
      ansible.builtin.set_fact:
        student_yaml: "{{ lookup('file', 'students.yaml') | from_yaml }}"

    - name: convert yaml to json
      ansible.builtin.debug:
        msg: "{{ student_yaml | to_nice_json }}"